IDE-2736: added a server that keeps JRuby in memory. Adjusted asciispec.

diff --git a/src/main/resources/asciispec b/src/main/resources/asciispec
--- a/src/main/resources/asciispec
+++ b/src/main/resources/asciispec
@@ -1,14 +1,42 @@
 #!/bin/bash
 
+
+# -e  == exit immediately
+# -x  == enable debug. (+x for disable)
+set -e +x
+
+
 # Set INVOCATION_HOME and APP_HOME
 INVOCATION_HOME="$(pwd)"
 cd "$(dirname $0)/.." >/dev/null
 APP_HOME="$(pwd -P)"
 cd "$INVOCATION_HOME" >/dev/null
 
+# The classpath is built from absolute paths since this script may be executed from anywhere.
+CLASSPATH="$APP_HOME/lib/asciispec-0.0.1-SNAPSHOT.jar"
+
+# Force use of Font Awesome icons & pass filename
+PARAMETERS="-a icons=font -B $INVOCATION_HOME"
+
+# Load Ruby extensions
+EXTENSIONS="-r $APP_HOME/res/ext/todo.rb"
+
+# Starts the AsciiSpec Server
+CMD_SERVER="java -Dfile.encoding=UTF-8 -cp $CLASSPATH eu.numberfour.asciispec.cli.AsciiSpecServer"
+
+# Executes asciispec directly
+CMD_ASCIISPEC="java -Dfile.encoding=UTF-8 -cp $CLASSPATH eu.numberfour.asciispec.cli.AsciiSpec $EXTENSIONS $PARAMETERS"
+
+# TCP connection
+DEV_TCP="/dev/tcp/localhost/45115"
+
+
+
+# DEPRECATED FUNCTIONS
 # Handle recursive calls. This assumes no output base path for the processed files, so that the genereated files are placed next to the original files.
 # All additional parameters are passed on to asciidoctor
 if [ "${1}" == "-R" ]; then
+	echo "The option '-R' is deprecated and will be removed soon."
 	find . -name '*.adoc' -exec $0 {} ${@:2} \;
 	exit 0
 fi
@@ -19,6 +47,7 @@ fi
 # $1: -R=some_path
 # All additional parameters are passed on to asciidoctor
 if [[ ${1} == -R=* ]]; then
+	echo "The option '-R' is deprecated and will be removed soon."
 	OUTPUT_BASEPATH="${1:3}"
 	if ! [[ "${OUTPUT_BASEPATH:-1}" == "/" ]]; then
 		OUTPUT_BASEPATH="${OUTPUT_BASEPATH}/"
@@ -39,18 +68,156 @@ if [ "${1}" == "-RX" ]; then
 	exec $0 "$3" -D "$OUTPUT_PATH" ${@:4}
 	exit 0
 fi
+# END OF DEPRECATED FUNCTIONS
 
-# The classpath is built from absolute paths since this script may be executed from anywhere.
-CLASSPATH="$APP_HOME/lib/asciispec-0.0.1-SNAPSHOT.jar"
 
-# Inform user of what's being passed to AsciidoctorJ
-# echo "AsciiSpec: converting $@"
 
-# Force use of Font Awesome icons & pass filename
-PARAMETERS="-a icons=font $@"
+function usage () {
+	cat <<EOF
+Usage: asciispec-server.sh [-hdcstlu]
+	
+	-h		prints this help
+	-d [args]	direct execution using asciispec
+	-c [args]	commit message to server
+	-l [args]	commit message to server; starts server lazily
+	-s		start server on port 45115
+	-t		terminate process on port 45115
+	-u		check if port 45115 is used currently
 
-# Load Ruby extensions
-EXTENSIONS="-r $APP_HOME/res/ext/todo.rb"
+EOF
+}
 
-# Run AsciidoctorJ and pass on all commandline parameters.
-java -Dfile.encoding=UTF-8 -cp $CLASSPATH eu.numberfour.asciispec.cli.AsciiSpec $PARAMETERS $EXTENSIONS
+
+function isUsedPort () {
+	set +e
+	exec 3<>$DEV_TCP
+
+	if [ "$?" -eq "0" ]; then
+		set -e
+	    return 0 #true
+	else
+		set -e
+	    return 1 #false
+	fi
+}
+
+
+function startServer () {
+	# check if already running
+	if isUsedPort; then
+	    echo "Server already started."
+	    return
+	fi
+
+	cmd=$CMD_SERVER $1
+	#nohup -p $!
+	nohup $cmd >/dev/null 2>&1 &
+	#nohup $cmd & tail -f nohup.out
+	#$cmd &
+	#wait
+	echo "Server started. PID: $!"
+	
+}
+
+
+function commit () {
+	cmd="$EXTENSIONS $PARAMETERS $1"
+
+	# establish connection
+	exec 3<>$DEV_TCP
+	# send query
+	echo "$cmd" >&3
+
+	# read and print results
+	read -r msg_in <&3
+	while [ "$msg_in" != "" ];
+	do
+		echo -e "$msg_in"
+		read -r msg_in <&3
+	done
+}
+
+
+function asciispec () {
+	$CMD_ASCIISPEC $1
+}
+
+
+function lazyCommit () {
+	if !(isUsedPort;) then
+	    startServer
+		sleep 1
+	fi
+
+	commit $1
+}
+
+
+function terminate () {
+	if !(isUsedPort;) then
+	    echo "No process running on port 45115."
+	    return
+	fi
+
+	kill -9 $(lsof -i:45115 -t)
+	echo "Killed process on port 45115."
+}
+
+while getopts ":hdcstlu" opt; do
+	case $opt in
+
+		h)
+			usage
+			exit 0
+			;;
+
+		d)
+			asciispec ${@:2}
+			exit 0
+			;;
+
+		s)
+			startServer ${2}
+			exit 0
+			;;
+		
+		t)
+			terminate
+			exit 0
+			;;
+				
+		c)
+			commit ${@:2}
+			exit 0
+			;;
+				
+		l)
+			lazyCommit ${@:2}
+			exit 0
+			;;
+		
+		u)
+			if (isUsedPort;) then
+			    echo "Port in use."
+			else
+			    echo "Port free."
+			fi
+
+			exit 0
+			;;
+
+
+		\?)
+			# If option unknown, give feedback, trigger 'usage' function
+			echo -e "[WARNING] Invalid option: -$OPTARG"
+			usage
+			exit 1
+			;;
+	esac
+done
+
+
+# No option passed. Use default case.
+#lazyCommit ${@:1}
+asciispec ${@:1}
+exit 0
